source 'http://rubygems.org'
gem 'mime-types', '2.0'
gem 'rest-client', '1.6.7'
gem 'nokogiri', '1.6.8'
gem 'nori', '2.6.0'
gem 'nokogiri-pretty', '0.1.0'
gem 'awesome_print', '1.7.0'
gem 'highline', '1.7.8'
