source 'http://rubygems.org'
gem 'mime-types', '2.0'
gem 'rest-client', '>= 1.7.3'
gem 'nokogiri', '1.8.2'
gem 'nori', '2.6.0'
gem 'nokogiri-pretty', '0.1.0'
gem 'awesome_print', '1.7.0'
gem 'highline', '1.7.8'
